openapi: 3.0.0
info:
  title: Grammar Tree API
  version: 1.0.0
description: API to generate and render trees based on provided grammars.
paths:
  /generate:
    post:
      summary: Generate a tree based on a given grammar and seed.
      operationId: generateTree
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                seed:
                  type: string
                  description: The seed symbol to start generating the tree.
                grammar:
                  type: string
                  description: The grammar string in CFG format.
                iterations:
                  type: integer
                  default: 5
                  description: The number of iterations for tree expansion.
      responses:
        '200':
          description: Successfully generated the tree.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tree'
        '400':
          description: Invalid input.

  /render:
    get:
      summary: Render a tree as a PNG image.
      operationId: renderTree
      parameters:
        - in: query
          name: tree
          required: true
          schema:
            $ref: '#/components/schemas/Tree'
          description: The tree to render.
      responses:
        '200':
          description: Successfully rendered the tree image.
          content:
            image/png:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid input.

components:
  schemas:
    Tree:
      type: object
      oneOf:
        - $ref: '#/components/schemas/Leaf'
        - $ref: '#/components/schemas/Branch'
      description: A tree structure which is either a leaf or a branch.
    Leaf:
      type: string
      description: A leaf node in the tree.
    Branch:
      type: object
      required:
        - symbol
        - children
      properties:
        symbol:
          type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/Tree'
      description: A branch in the tree with a symbol and children nodes.
